title = "Custom Gitleaks Config"

[allowlist]
files = [
    "package-lock.json", 
    "node_modules/" 
  ]
regexes = [
    "https://registry\\.npmjs\\.org",
    "(?i)password",
    "(?i)reset[pP]assword",
    "(?i)forgot[pP]assword",
    "(?i)use[rR]eset[pP]assword[fF]orm",
    "(?i)use[fF]orgot[pP]assword[fF]orm"
]
paths = [
    "package-lock.json",
    "components/reusable-components/forgot-password-form/ForgotPasswordForm.tsx",
    "components/reusable-components/reset-password-form/ResetPasswordForm.tsx",
    "utils/hooks/usePasswordForm.ts"
]

# Rule to detect API keys
[[rules]]
id = "apikey"
description = "API Key"
regex = '''[A-Za-z0-9_]{32,}'''
tags = ["apikey"]

# Rule to detect Google API Keys
[[rules]]
id = "google_apikey"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z-_]{35}'''
tags = ["apikey"]

# Rule to detect URLs
[[rules]]
id = "url"
description = "URLs"
regex = '''https?://[^\s]+'''
tags = ["url"]

# Rule to detect passwords
[[rules]]
id = "password"
description = "Match passwords"
regex = '''(?i)(password|pwd|pass|passwd)([=:].+)?[ \t]*(\S+)'''
tags = ["password"]
[rules.allowlist]
regexes = [
    "(?i)password",
    "(?i)reset[pP]assword",
    "(?i)forgot[pP]assword",
    "(?i)use[rR]eset[pP]assword[fF]orm",
    "(?i)use[fF]orgot[pP]assword[fF]orm"
]

# Rule to detect SSH keys
[[rules]]
id = "ssh_key"
description = "Match SSH keys"
regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY----'''
tags = ["ssh_key"]
