// eslint-disable-next-line no-unused-vars, no-unused-expressions

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Suspense } from 'react';
import './styles/main.scss';
import Loading from './loading';
<<<<<<< HEAD
import { ThemeProvider } from '../components/context/ThemeContext';
=======
import Footer from '../components/reusable-components/footer/Footer';
import Navigation from '../components/reusable-components/navigation/Navigation';
>>>>>>> main

const roboto = Roboto({ subsets: ['latin'], weight: ['400'] });

const RootLayout = ({
  children,
}: Readonly<{
  // eslint-disable-next-line no-undef
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={roboto.className}>
      <Navigation />
      <main>
        <Suspense fallback={<Loading />}>
          <ThemeProvider>{children}</ThemeProvider>
        </Suspense>
      </main>
      <Footer />
    </body>
  </html>
);

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default RootLayout;
