import React, { Suspense } from 'react';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import './styles/main.scss';
import Loading from './loading';
import Footer from '../components/reusable-components/footer';
import Navigation from '../components/reusable-components/navigation';

const roboto = Roboto({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main>
          <Navigation />
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </main>
        <Footer />
      </body>
    </html>
  );
}
